theme = "nvim-theme"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "multiple"
popup-border = "all"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
right = ["diagnostics", "selections", "position", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
